#file: noinspection invalidValue,PropertyDeprecated,undefined

resilience4j:
  circuitbreaker:
    configs:
      porDefecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: porDefecto
  timelimiter:
    configs:
      porDefecto:
        timeout-duration: 3s
    instances:
      products:
        base-config: porDefecto

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
#            - Header=token, 12345
#            - Method=GET, POST
#            - Query=color, verde #queryParam
#            - Cookie=color, azul
          filters:
            - name: CircuitBreaker
              args:
                name: products # Crea un filtro CircuitBreaker con el nombre de products de cortocircuito y toma su config del yml
                statusCodes: 500 # Indica que errores son contados para el circuit breaker
                fallbackUri: forward:/api/items/5 # Se debe redireccionar a otro servicio que no sea el que dio error
            - StripPrefix=2
            - name: SampleCookie # Nombre del filtro sin el postfijo GatewayFilterFactory, se puede dar
              # un nombre espec√≠fico con el metodo name del filtro
              args:
                message: Hola mi mensaje personalizado para productos!
                name: user
                value: Dani

        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, aaabbbdsdfaeg
            - AddResponseHeader=token-response, 3542363
            - AddRequestParameter=name, Daniel
            - SetResponseHeader=Content-Type, text-plain # set modifica un header ya existente